import { JetBrains_Mono } from "next/font/google";
import "./globals.css";

import Hotbar from "@/components/mc/Hotbar";
import KonamiUnlock from "@/components/room/easter-eggs/KonamiUnlock";
import ConsoleEasterEgg from "@/components/room/easter-eggs/ConsoleEasterEgg";

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-jetbrainsMono",
});

const description =
  "Portfolio of Saurabh Nair, software developer and CS + Economics student at the University of Toronto. Explore my pixel-art 3D room.";

// Link previews (LinkedIn, Discord, iMessage...) use public/og.png, a snapshot
// of the home page regenerated by `npm run poster`. Vercel sets the production URL.
export const metadata = {
  metadataBase: new URL(
    process.env.VERCEL_PROJECT_PRODUCTION_URL ? `https://${process.env.VERCEL_PROJECT_PRODUCTION_URL}` : "https://saur-portofolio.vercel.app"
  ),
  title: "Saurabh Nair — Software Developer",
  description,
  openGraph: {
    title: "Saurabh Nair — Software Developer",
    description,
    images: [{ url: "/og.png", width: 1200, height: 630, alt: "Saurabh's pixel-art 3D room portfolio" }],
    type: "website",
  },
  twitter: { card: "summary_large_image", images: ["/og.png"] },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jetbrainsMono.variable}>
        {children}
        <Hotbar />
        <KonamiUnlock />
        <ConsoleEasterEgg />
      </body>
    </html>
  );
}
