import { JetBrains_Mono } from "next/font/google";
import "./globals.css";

import { Analytics } from "@vercel/analytics/next";
import Sidebar from "@/components/room/Sidebar";
import SiteNav from "@/components/room/SiteNav";
import { profile, SITE } from "@/data/portfolio";
import KonamiUnlock from "@/components/room/easter-eggs/KonamiUnlock";
import ConsoleEasterEgg from "@/components/room/easter-eggs/ConsoleEasterEgg";

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-jetbrainsMono",
});

const description =
  "Portfolio of Saurabh Nair, software developer and CS + Economics student at the University of Toronto. Explore my pixel-art 3D room.";

// Link previews (LinkedIn, Discord, iMessage...) use public/og.png, a snapshot
// of the home page regenerated by `npm run poster`. Pages set their own title
// (via the template) and canonical path.
export const metadata = {
  metadataBase: new URL(SITE),
  title: { default: "Saurabh Nair — Software Developer", template: "%s — Saurabh Nair" },
  description,
  alternates: { canonical: "/" },
  openGraph: {
    title: "Saurabh Nair — Software Developer",
    description,
    images: [{ url: "/og.png", width: 1200, height: 630, alt: "Saurabh's pixel-art 3D room portfolio" }],
    type: "website",
  },
  twitter: { card: "summary_large_image", images: ["/og.png"] },
};

export const viewport = { themeColor: "#1c1c22" };

// Structured data so searches for my name can show the right person and links.
const PERSON = {
  "@context": "https://schema.org",
  "@type": "Person",
  name: profile.name,
  jobTitle: profile.role,
  url: SITE,
  alumniOf: { "@type": "CollegeOrUniversity", name: "University of Toronto" },
  sameAs: profile.socials.filter((s) => s.href.startsWith("http")).map((s) => s.href),
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jetbrainsMono.variable}>
        {/* sidebar (3D me, name, socials) beside every page; the page fills the rest */}
        <div className="mx-auto max-w-[1800px] px-4 lg:px-8 pt-3 grid grid-cols-1 gap-4 lg:gap-6 lg:grid-cols-[260px_1fr]">
          <Sidebar />
          <main className="min-w-0">
            <SiteNav />
            {children}
          </main>
        </div>
        <KonamiUnlock />
        <ConsoleEasterEgg />
        <Analytics />
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(PERSON) }} />
      </body>
    </html>
  );
}
